name: pr-reviewer-agent
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - langchain>=0.3.26
    - langchain-openai>=0.3.24
    - fastapi>=0.100.0
    - uvicorn>=0.23.0
    - pydantic>=2.0.0
    - python-dotenv>=1.0.0
    - PyYAML>=6.0.1
    - aiohttp>=3.8.5
    - pytest>=7.4.0
    - black>=23.7.0
    - isort>=5.12.0
    - flake8>=6.1.0
    - mypy>=1.5.0